route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: ['alertname']

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'pragyaawasthi248@gmail.com'
        auth_password: 'password123'
        from: 'awasthipragya66@gmail.com'
        to: 'pragyaawasthi248@gmail.com'

