global:
  scrape_interval: 15s  # Frequency of metric scraping

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

# ... other Prometheus configuration ...

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] # Use the service name and port

  rule_files:
    - "alerts.rules.yml"
